server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # For prometheus metrics if NGINX exporter is used, though usually handled differently.
    location /metrics {
        stub_status;
    }
}
